---
- name: Include update_fit.yml
  ansible.builtin.include_tasks: update_fit.yml

# - name: Include update_apt.yml
#   ansible.builtin.include_tasks: update_apt.yml

- name: Install NetworkManager
  ansible.builtin.include_tasks: networkmanager.yml

- name: Install extra packages
  ansible.builtin.apt:
    pkg:
      - fish
      - fzf
      - htop
      - micro
    update_cache: true
