---
- name: Copy /etc/wb-mqtt-serial.conf
  ansible.builtin.template:
    src: wb-mqtt-serial.conf.j2
    dest: /etc/wb-mqtt-serial.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Restart service wb-mqtt-serial
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: wb-mqtt-serial

- name: Copy rules.js
  ansible.builtin.copy:
    src: rules.js
    dest: /etc/wb-rules/rules.js
    owner: root
    group: root
    mode: '0644'

- name: Restart service wb-rules
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: wb-rules
