---
- name: Create /mnt/data/var/tmp
  ansible.builtin.file:
    path: /mnt/data/var/tmp
    state: directory
    mode: '0777'

- name: Create /mnt/data/var/lib/containers
  ansible.builtin.file:
    path: /mnt/data/var/lib/containers
    state: directory
    mode: '0777'

- name: Create /var/lib/containers
  ansible.builtin.file:
    src: /mnt/data/var/lib/containers
    dest: /var/lib/containers
    state: link

- name: Install podman
  become: true
  ansible.builtin.apt:
    pkg:
      - podman
    state: present
    update_cache: true
