---
- name: Add the user 'user'
  ansible.builtin.user:
    name: user
    comment: WB user
    group: users
    home: /mnt/data/user
    password: $6$TAwiuBFg80WAExrX$KbIehXImdbR5dT9d0dINhbJCBlPgkZEez.oO359GPxrPwtsik36wP4nynMyEbUlfSximlygP3VU6.pNbMgFm.1

- name: Create /mnt/data/var/tmp
  ansible.builtin.file:
    path: /mnt/data/var/tmp
    state: directory
    mode: '0777'

- name: Install podman
  become: true
  ansible.builtin.apt:
    pkg:
      - podman
    state: present
    update_cache: true
