---
- name: Copy /etc/network/interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy /etc/hostapd.conf
  ansible.builtin.template:
    src: hostapd.conf.j2
    dest: /etc/hostapd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

#- name: Restart service hostapd
#  ansible.builtin.service:
#    name: hostapd
#    state: restarted

- name: Up wlan1
  ansible.builtin.command: ifup wlan1

#- name: Copy wifi_autoconnect.sh
#  ansible.builtin.copy:
#    src: wifi_autoconnect.sh
#    dest: /root/wifi_autoconnect.sh
#    owner: root
#    group: root
#    mode: '0755'

#- name: Automatic reconnection
#  ansible.builtin.cron:
#    name: Automatic reconnection
#    job: /root/wifi_autoconnect.sh
