---
- name: Add tailscale signing key
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'

- name: Add tailscale deb
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bullseye main"
    state: present

- name: Install tailscale
  become: true
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true
