---
- name: Set net.ipv4.ip_forward=1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Set net.ipv6.conf.all.forwarding=1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Configure Tailscale
  include_role:
    name: artis3n.tailscale
  vars:
    tailscale_args: "--advertise-exit-node"
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
