---
- name: Set authorized key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set timezone
  community.general.timezone:
    name: '{{ tz }}'
    hwclock: local
