---
- name: Copy FIT image
  ansible.builtin.copy:
    src: ./latest.fit
    dest: /mnt/data/update_image.fit
    mode: '0644'

- name: Update firmware
  ansible.builtin.shell: |
    nohup wb-run-update /mnt/data/update_image.fit >/dev/null 2>&1 &

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    delay: 360
    timeout: 1200

- name: Set authorized key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set timezone
  community.general.timezone:
    name: '{{ tz }}'
    hwclock: local

- name: Set mosquitto log
  ansible.builtin.replace:
    path: /etc/mosquitto/mosquitto.conf
    regexp: "^log_dest (.+)$"
    replace: "log_dest syslog"

- name: Create password for mosquitto
  ansible.builtin.shell: |
    mosquitto_passwd -b /etc/mosquitto/passwd/default.conf root wirenboard

- name: Disable anonymous access
  ansible.builtin.replace:
    path: /etc/mosquitto/conf.d/10listeners.conf
    regexp: "^allow_anonymous true$"
    replace: "allow_anonymous false"

- name: Update mosquitto ACL
  ansible.builtin.lineinfile:
    path: /etc/mosquitto/acl/default.conf
    insertbefore: "BOF"
    line: "user root"

- name: Restart mosquitto
  ansible.builtin.systemd:
    state: restarted
    name: mosquitto

- name: Get controller's serial number
  ansible.builtin.slurp:
    src: /mnt/data/var/lib/wirenboard/short_sn.conf
  register: snid

- name: Update AP mode wifi connection
  community.general.nmcli:
    type: wifi
    conn_name: "wb-ap"
    ifname: wlan0
    ssid: "WirenBoard-{{ snid['content'] | b64decode }}"
    wifi:
      mode: ap
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "wirenboard"
      wps-method: 1
    autoconnect: true
    state: present

- name: Add client mode wifi connection
  community.general.nmcli:
    type: wifi
    conn_name: "{{ lookup('env', 'SSID') }}"
    dns4:
      - "1.1.1.1"
      - "8.8.8.8"
    ifname: wlan1
    ssid: "{{ lookup('env', 'SSID') }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ lookup('env', 'PSK') }}"
    autoconnect: true
    state: present

# - name: Empty /etc/network/interfaces
#   ansible.builtin.shell: echo > /etc/network/interfaces

- name: Add the user 'user'
  ansible.builtin.user:
    name: user
    comment: WB user
    group: users
    home: /mnt/data/user
    password: $6$TAwiuBFg80WAExrX$KbIehXImdbR5dT9d0dINhbJCBlPgkZEez.oO359GPxrPwtsik36wP4nynMyEbUlfSximlygP3VU6.pNbMgFm.1

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install extra packages
  ansible.builtin.apt:
    pkg:
      - fish
      - fzf
      - gdb
      - htop
      - micro
      - sudo
      - systemd-coredump
      - tmux

- name: Run tmux on ssh login
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: |
      if [[ -z $TMUX ]] && [[ -n $SSH_TTY ]]; then
        exec tmux new-session -A -s wb-session
      fi
