---
- name: Install iptables
  become: true
  ansible.builtin.apt:
    name: iptables
    state: present
    update_cache: true

- name: Add the ip_tables module
  community.general.modprobe:
    name: ip_tables

- name: Enable translation
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"

- name: Start translation
  ansible.builtin.shell: |
    echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Set up translation rules
  ansible.builtin.shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
    iptables -A FORWARD -i wlan1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT
    iptables-save > /etc/iptables.ipv4.nat

- name: Restore translation rules
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "up iptables-restore < /etc/iptables.ipv4.nat"
