---
  - name: WB7 mqtt-serial playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - ../vars.yml
    tasks:
      - name: Copy /etc/wb-mqtt-serial.conf
        ansible.builtin.template:
          src: ../etc/wb-mqtt-serial.conf.j2
          dest: /etc/wb-mqtt-serial.conf
          owner: root
          group: root
          mode: '0644'
          backup: yes

      - name: Restart service wb-mqtt-serial
        ansible.builtin.systemd:
          state: restarted
          daemon_reload: yes
          name: wb-mqtt-serial
