---
  - name: WB7 timezone playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - ../vars.yml
    tasks:
      - name: Set timezone
        community.general.timezone:
          name: Europe/Moscow
          hwclock: local
