---
  - name: WB7 testing playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - ../config.yml
    tasks:
      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes

      - name: Switch to testing
        ansible.builtin.command: wb-release -y -t testing

      - name: Update to Debian Bullseye
        ansible.builtin.command: wb-release -y --update-debian-release

      - name: Install packages
        ansible.builtin.apt:
          pkg:
          - htop
          - wb-nm-helper

      - name: Enable service hostapd
        ansible.builtin.systemd:
          name: hostapd
          enabled: yes
