---
  - name: WB7 telegram playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - ../config.yml
    tasks:
      - name: Download telegram2wb module
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/wb-adegtyarev/telegram2wb/main/src/telegram2wb.js
          dest: /etc/wb-rules-modules/telegram2wb.js

      - name: Restart service wb-rules
        ansible.builtin.systemd:
          state: restarted
          daemon_reload: yes
          name: wb-rules
