---
  - name: WB7 network playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - ../config.yml
    tasks:
      - name: Copy /etc/network/interfaces
        ansible.builtin.template:
          src: ../etc/network/interfaces.j2
          dest: /etc/network/interfaces
          owner: root
          group: root
          mode: '0644'
          backup: yes

      - name: Copy /etc/hostapd.conf
        ansible.builtin.template:
          src: ../etc/hostapd.conf.j2
          dest: /etc/hostapd.conf
          owner: root
          group: root
          mode: '0644'
          backup: yes

      - name: Up wlan1
        ansible.builtin.command: ifup wlan1
