---
  - name: WB7 setup playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - vars.yml
    tasks:
      - name: Set timezone
        community.general.timezone:
          name: Europe/Moscow
          hwclock: local

      - name: Copy /etc/network/interfaces
        ansible.builtin.template:
          src: etc/network/interfaces.j2
          dest: /etc/network/interfaces
          owner: root
          group: root
          mode: '0644'
          backup: yes

      - name: Copy /etc/hostapd.conf
        ansible.builtin.template:
          src: etc/hostapd.conf.j2
          dest: /etc/hostapd.conf
          owner: root
          group: root
          mode: '0644'
          backup: yes

      - name: Up wlan1
        ansible.builtin.command: ifup wlan1

      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes

      - name: Switch to testing
        ansible.builtin.command: wb-release -y -t testing

      - name: Update to Debian Bullseye
        ansible.builtin.command: wb-release -y --update-debian-release

      - name: Enable service hostapd
        ansible.builtin.systemd:
          name: hostapd
          enabled: yes

      - name: Reboot
        ansible.builtin.reboot:
