---
  - name: Node-RED setup playbook
    gather_facts: false
    hosts: all
    remote_user: root
    vars_files:
      - vars.yml
    tasks:
      - name: Install packages
        ansible.builtin.apt:
          pkg:
          - nodejs
          - git
          - make
          - g++
          - gcc
          - build-essential

      - name: Install Node-RED
        community.general.npm:
          name: node-red
          global: true
          unsafe_perm: true

      - name: Copy /etc/systemd/system/nodered.service
        ansible.builtin.copy:
          src: etc/systemd/system/nodered.service
          dest: /etc/systemd/system/nodered.service
          owner: root
          group: root
          mode: '0644'

      - name: Enable service nodered
        ansible.builtin.systemd:
          name: nodered
          enabled: yes
